port:  5000
encoding: utf-8
title: ReEntry Co Lab
email: reentrycolab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We're a coalition of Chicago community organizations working to create better
  and more accessible re-entry services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reentryco-lab.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:
collections:
  - members
  - events

# Build settings
markdown: kramdown
